# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'XYBaseListView', :git => 'git@github.com:ygg29/XYBaseListView.git',  :branch => 'master'


end
